### ISSUE TITLE
multi-progress npm module released

### ISSUE THREAD

**Issue by pitaj** [visionmedia/node-progress#108]
[multi-progress](/pitaj/multi-progress) is now a [package on npm](https://www.npmjs.com/package/multi-progress)

This module adds a layer on top of the API of progress that allows for multiple progress bars. It is based on the [gist](https://gist.github.com/nuxlli/b425344b92ac1ff99c74)  by @nuxlli

I used it in my [rslashimg](/pitaj/rslashimg) package, and it seems to work just fine.

Should I send in a PR adding this to the progress readme?

**Comment by hallas** [comment]
Yes please :)
