### ISSUE TITLE
Inability to force close / interrupt process

### ISSUE THREAD

**Issue by rudbast** [visionmedia/node-progress#126]
As the title says, I am unable to "force close" the node process by pressing `Ctrl + C` when the progress bar has not finished its job. I had to close the terminal / manually kill the process in other window to force close the node process. Is this normal ?

**Comment by thebigredgeek** [comment]
Hmm, I am doubtful that the library itself is causing this.  Can you post a gist of your code?  I've never seen that happen unless I am doing a massive blocking operation.  `Ctrl + C` essentially sends the process an event, which Node won't interpret until it has a free turn, so a blocking operation would delay the processing of said event.

**Comment by rudbast** [comment]
Hi, thanks for the confirmation. I've verified it myself, and yeah, the `Ctrl + C` do actually work (on other code). It's just as you said, my code is doing a massive blocking operation, here's the [piece of code](https://gist.github.com/rudbast/1b6714d7bc1f8f4df3f34e3645f59113) if you're interested.

I didn't know that this is a thing before (blocking operation affect `Ctrl + C`), thanks again for the help.
