### ISSUE TITLE
Invalid Array Length when window has low width

### ISSUE THREAD

**Issue by cchamberlain** [visionmedia/node-progress#130]
When using lerna I'm getting its bootstrap failing sometimes when the window has very low width.

![image](https://cloud.githubusercontent.com/assets/424694/16919361/34d62988-4cbe-11e6-8807-145f3952d137.png)

This is on Windows 10, node `v6.2.2`, npm `3.10.6`.

**Comment by thejameskyle** [comment]
Should be able to do:

```js
Array(Math.max(0, width - completeLength + 1))
```


Want to make a PR?

**Comment by cchamberlain** [comment]
Sure, will try an toss it together in the morning.
