### ISSUE TITLE
bar.interrupt() doesn't exist

### ISSUE THREAD

**Issue by Whipgit** [visionmedia/node-progress#137]
In the docs you explain the bar.interrupt() functionality... but in ./lib/node-progress of the npm-installed package, the prototype is not added to the object.

I can see it in the repo here, but the npm module does not match it.

**Comment by tproenca** [comment]
Some issue in here.

**Comment by charlesvinette** [comment]
+1

**Comment by thebigredgeek** [comment]
This should be fixed in the release that i just pushed.  Thank you for your patience :)
