### ISSUE TITLE
Issue with package version

### ISSUE THREAD

**Issue by overra** [visionmedia/node-progress#140]
I'm using `stream-progressbar` which depends on `progress@^1.1.8` which is the version in the current `package.json` but according to the [git history](https://github.com/visionmedia/node-progress/blob/bca8895cb7bd370d89d7021ebb4d7a1ba74532c6/package.json) `1.2.0` has already been released but it looks like the history got messed up and `package.json` shows `1.1.8` as the current version. I'm confused as to how this happened, how could it be overwritten without showing up in history?

[Current package.json](https://github.com/visionmedia/node-progress/blame/master/package.json)  
[1.2.0 package.json](https://github.com/visionmedia/node-progress/blame/bca8895cb7bd370d89d7021ebb4d7a1ba74532c6/package.json)

❤️

**Comment by Whipgit** [comment]
Yeah, it prevents us from using some features. Like .interrupt()

**Comment by ahmetcetin** [comment]
the same here, until the version in package.json bumped, i've added 
"progress": "visionmedia/node-progress"
in my package.json

**Comment by thebigredgeek** [comment]
Release 2.0.0 is live.  Sorry about the stagnation.  I plan on keeping this project well maintained moving forward
