### ISSUE TITLE
Coloured bars?

### ISSUE THREAD

**Issue by Iambecomeroot** [visionmedia/node-progress#163]
Is there any way to colour the bar? Maybe with [chalk](https://www.npmjs.com/package/chalk)?

**Comment by jHoldroyd** [comment]
Chalk works well, you just need to wrap the replacements in your bar style, something like this:

``` js
let style = 'downloading [' + chalk.magenta(':bar') + '] :rate/bps ' + chalk.green(':percent') + ' :etas'
let bar = new ProgressBar(style, {
  complete: '=',
  incomplete: ' ',
  width: 20,
  total: len
})
```

**Comment by Iambecomeroot** [comment]
@jHoldroyd Thanks! I should try things before submitting issues...
