### ISSUE TITLE
Error when using shippable

### ISSUE THREAD

**Issue by arunoda** [visionmedia/node-progress#95]
I'm getting this error when used progress inside a service called Shippable. (a CI server)
I'm using progress@1.1.5.
What should be the issue?

```
/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/progress/lib/node-progress.js:168
this.stream.clearLine();
^
TypeError: Object # has no method 'clearLine'
at ProgressBar.terminate (/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/progress/lib/node-progress.js:168:17)
at ProgressBar.tick (/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/progress/lib/node-progress.js:91:10)
at ProgressBar.update (/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/progress/lib/node-progress.js:157:8)
```

**Comment by jdan** [comment]
Can you elaborate a little more on how you're using the progress module? Can you paste the code that uses it?

**Comment by arunoda** [comment]
Sure.
See: https://github.com/arunoda/nodemiral/blob/46371b38db0ff6be87747c0c492df793d5c87724/lib/session.js#L110

**Comment by jrouleau** [comment]
I don't see anything directly wrong with your usage. You're not setting a custom stream, so we default to `process.stderr`. Is your application doing anything funny to the default streams or perhaps running in an environment where they don't exists? Maybe you need to pass a custom stream with the `stream` option? See the [Readme](https://github.com/tj/node-progress/blob/master/Readme.md) for more information.

I have run mocha on both arunoda/nodemiral@3f90a0a7ac65df0ab3d3462a58149005ae5cd815 (master) and arunoda/nodemiral@46371b38db0ff6be87747c0c492df793d5c87724 and am not receiving any failures.

**Comment by arunoda** [comment]
I don't get this normally as well. May be something with the shippable
infrastructure. I'll keep digging.

**Comment by bahmutov** [comment]
I have the same error trying to use inside the Docker container

**Comment by bahmutov** [comment]
Example code causing a problem
```js
var ProgressBar = require('progress');

var bar = new ProgressBar(':bar', { total: 10 });
var timer = setInterval(function () {
  bar.tick();
  bar.clear = true
  bar.terminate()
  if (bar.complete) {
    console.log('\ncomplete\n');
    clearInterval(timer);
  }
}, 100);
```
Dockerfile for this
```
from node:7
copy package.json /
run npm install
copy index.js /
cmd ["node", "index.js"]
```
Build image and run it command
```
docker build -t progress .
docker run progress
```
Error in the output
```
/node_modules/progress/lib/node-progress.js:177
    this.stream.clearLine();
                ^
TypeError: this.stream.clearLine is not a function
    at ProgressBar.terminate (/node_modules/progress/lib/node-progress.js:177:17)
    at Timeout._onTimeout (/index.js:7:7)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by bahmutov** [comment]
A simple guard prevents the crash
```js
ProgressBar.prototype.terminate = function () {
  if (this.clear) {
    if (this.stream.clearLine) {
      this.stream.clearLine();
      this.stream.cursorTo(0);
    }
  } else console.log();
};
```

**Comment by sabberworm** [comment]
There are still two usages of `stream.clearLine` left that would also need a guard.

* https://github.com/visionmedia/node-progress/blob/0790207ef077cbfb7ebde24a1dd9895ebf4643e1/lib/node-progress.js#L176
* https://github.com/visionmedia/node-progress/blob/0790207ef077cbfb7ebde24a1dd9895ebf4643e1/lib/node-progress.js#L210
